### ISSUE TITLE
我没有显示啊

### ISSUE THREAD

**Issue by linxiazhixi** [NiaoBlush/weibo-ip-location#3]
进去关注人主页个人信息有定位信息，但是我的主页刷到时候依然不显示地址

**Comment by HoleenLu** [comment]
我的也没有显示，应该是非新版微博网页不显示。只有V7版网页才显示的样子。

**Comment by linxiazhixi** [comment]
> 我的也没有显示，应该是非新版微博网页不显示。只有V7版网页才显示的样子。

果然是只有新版能显示，旧版没有。那只能不用这脚本了。。我用着药方，只能旧版

**Comment by NiaoBlush** [comment]
> 我的也没有显示，应该是非新版微博网页不显示。只有V7版网页才显示的样子。

我之前电脑点不亮了, 晚上看看.
旧版界面应该怎么进?

**Comment by linxiazhixi** [comment]
> > 我的也没有显示，应该是非新版微博网页不显示。只有V7版网页才显示的样子。
> 
> 我之前电脑点不亮了, 晚上看看. 旧版界面应该怎么进?

右上角设置下面有个返回原版微博

**Comment by NiaoBlush** [comment]
已适配v6版
4990c268139b77c950121fc12c1fe56e05670b6b
